# 0. SETUP

In [1]:
import os 
os.environ["PIP_QUIET"] = "1"

In [2]:
# Install required libraries and Run them only once
!pip install pandas openpyxl torch transformers scikit-learn matplotlib seaborn wandb
!pip install bertopic sentence-transformers wordcloud
!pip install nltk beautifulsoup4 contractions emoji pyspellchecker langdetect

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [3]:
import pandas as pd
from nltk.collocations import BigramCollocationFinder
from nltk.collocations import BigramAssocMeasures
import nltk
import numpy as np
import matplotlib.pyplot as plt
import pyLDAvis
import pyLDAvis.gensim_models
from gensim import corpora
from gensim.models import LdaModel
import re
import argparse
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
# Plotly imports
import plotly.offline as py
py.init_notebook_mode(connected=True)
import plotly.graph_objs as go
import plotly.tools as tls
from matplotlib import pyplot as plt
%matplotlib inline

/Users/khnsakhnm/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

# 1. Loading Train and Test data

In [4]:
import sys
!{sys.executable} -m pip install openpyxl

WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [5]:
import openpyxl

train_1 = pd.read_excel("/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/raw_input/Coding - Gavin.xlsx")
train_2 = pd.read_excel("/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/raw_input/Coding - Katie Complete 2.18.26.xlsx")

train = pd.concat([train_1, train_2], ignore_index=True)

cols = ['Functional', 'Relational', 'Metaphysical', 'Technical']
train[cols] = train[cols].apply(pd.to_numeric, errors='coerce').astype('Int64')
train.columns = train.columns.str.lower()
train.drop(columns=['relational', 'metaphysical', 'technical'], inplace=True)

train.head()

                                                text  functional
0  this whole thread is rough to read. i think ev...           0
1  I'm developing a solve for exactly this - a jo...           1
2  I don't know if this has been reported here ye...          99
3  https://preview.redd.it/lj49iq34it9f1.jpeg?wid...          99
4  https://preview.redd.it/4mfmbgmd3kcg1.jpeg?wid...          99

In [6]:
train.to_csv("/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/train.csv", index=False)

In [7]:
test = pd.read_csv("/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/raw_input/cleaned_combined_posts_comments.csv")
test.head()
test.columns = test.columns.str.lower()
test.to_csv("/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/test.csv", index=False)

In [8]:
test.head()

,id,parent_id,type,text,score,created_utc,index
0,1jvg6gw,NaN,post,,1,1744231180,1
1,1jx1pxy,NaN,post,this space isnt about replacing therapists its...,1,1744408477,2
2,1jxkyee,NaN,post,one of the weirdest and most useful things abo...,4,1744474650,6
3,1jzpmtb,NaN,post,hey im mike i started this subreddit because i...,8,1744717048,7
4,1k10bvs,NaN,post,ive been in and out of therapy for most of my ...,15,1744851085,8

# 2. Data Pre-Processing

In [24]:
base_path = os.getcwd()
train_path = "/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/train.csv"
test_path = "/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/test.csv"

In [10]:
'''
Reads and cleans training and test CSV data for the
AI mental health Reddit study.

INPUTS:
1. data/train.csv
2. data/test.csv

LABEL COLUMNS (train only):
{Functional, Relational, Metaphysical, Technical}
Each coded as: 1=positive  0=neutral  -1=negative  99=not_mentioned
'''

%run run_preprocessing.py --train_path {train_path} --test_path {test_path}

# Comment out the above line after running once to avoid re-processing every time you run this notebook

Preprocessor: TextPreprocessor(use_stemming=False, use_lemma=True, remove_stopwords=True, expand_contractions=True, handle_emojis=True, handle_negation=True, handle_chatwords=True, spell_check=False, language='english')

Loading training data from /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/train.csv...
  Shape: (801, 2)
  Removed/deleted : 1
  Image-only      : 5
  Running TextPreprocessor on training data...
  Flagged 133 posts as too short.
  Sample:
0    whole thread rough read think everyone look be...
1    developing solve exactly journalling tool prov...
2    not_know reported yet also little annoyed new ...
 Processed training data:

Loading test data from /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/test.csv...
  Shape: (19240, 7)
  Removed/deleted : 2
  Image-only      : 0
  Running TextPreprocessor on test data in batches of 1000...
  Processed 1000 / 19240 rows...
  Processed 2000 / 19240 rows...
  Processed 3000 / 19240 rows...
  Processed 4000 / 19240 rows...
  Processed 5000 / 19240 rows...
  Processed 6000 / 19240 rows...
  Processed 7000 / 19240 rows...
  Processed 8000 / 19240 rows...
  Processed 9000 / 19240 rows...
  Processed 10000 / 19240 rows...
  Processed 11000 / 19240 rows...
  Processed 12000 / 19240 rows...
  Processed 13000 / 19240 rows...
  Processed 14000 / 19240 rows...
  Processed 15000 / 19240 rows...
  Processed 16000 / 19240 rows...
  Processed 17000 / 19240 rows...
  Processed 18000 / 19240 rows...
  Processed 19000 / 19240 rows...
  Processed 19240 / 19240 rows...
Text preprocessing complete for 19240 rows.
  Flagged 2826 posts as too short.
  Sample:
0
1    space not_about replacing therapist exploring ...
2    one weirdest useful thing using ai self reflec...
 Processed test data:

Preprocessing complete for Training and Testing datasets


  Train : 801 posts | 5 images | 1 removed | 133 too short
  Test  : 19240 posts | 0 images | 2 removed | 2826 too short
  ⚠️  Remember to comment out %run run_preprocessing.py in main file

In [11]:
# Quick Sanity Check 
train_df = pd.read_csv(train_path)

print(f"Train rows: {train_df.shape[0]} \n")
print(f"Train columns: {train_df.shape[1]} \n")
print(train_df.head())

Train rows: 801

Train columns: 6

                                                text  functional  is_removed  \
0  this whole thread is rough to read. i think ev...         0.0       False
1  I'm developing a solve for exactly this - a jo...         1.0       False
2  I don't know if this has been reported here ye...        99.0       False
3  https://preview.redd.it/lj49iq34it9f1.jpeg?wid...        99.0       False
4  https://preview.redd.it/4mfmbgmd3kcg1.jpeg?wid...        99.0       False

   is_image                                       cleaned_text  too_short
0     False  whole thread rough read think everyone look be...      False
1     False  developing solve exactly journalling tool prov...      False
2     False  not_know reported yet also little annoyed new ...      False
3      True                                                NaN       True
4      True                                                NaN       True

In [12]:
# Quick Sanity Check
test_df = pd.read_csv(test_path)

print(f"Test rows: {test_df.shape[0]} \n")
print(f"Test columns: {test_df.shape[1]} \n")   
print(test_df.head())

Test rows: 19240

Test columns: 11

        id parent_id  type                                               text  \
0  1jvg6gw       NaN  post
1  1jx1pxy       NaN  post  this space isnt about replacing therapists its...
2  1jxkyee       NaN  post  one of the weirdest and most useful things abo...
3  1jzpmtb       NaN  post  hey im mike i started this subreddit because i...
4  1k10bvs       NaN  post  ive been in and out of therapy for most of my ...

   score  created_utc  index  is_removed  is_image  \
0      1   1744231180      1        True     False
1      1   1744408477      2       False     False
2      4   1744474650      6       False     False
3      8   1744717048      7       False     False
4     15   1744851085      8       False     False

                                        cleaned_text  too_short
0                                                NaN       True
1  space not_about replacing therapist exploring ...      False
2  one weirdest useful thing using ai self reflec...      False
3  hey mike started subreddit using ai especially...      False
4  therapy life diagnosed depression around age 1...      False

# 3. Exploratory Data Analysis

In [13]:
%run EDA.py \
    --train {train_path} \
    --test {test_path}

Loading /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/train.csv...
  Shape: (801, 6)

Loading /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/test.csv...
  Shape: (19240, 11)

[1/10] Label distribution (train)...
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/functional_class_distribution.png

  Label breakdown:
    positive          :  192  (24.0%)
    neutral           :   56  (7.0%)
    negative          :   54  (6.7%)
    not_mentioned     :  497  (62.0%)

[2/10] Text length — train vs test...
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/text_length_train_vs_test.png

  Token length stats:
    Train  mean=38.8  median=19.0  max=584
    Test  mean=39.1  median=19.0  max=2865

[3/10] Token length by label (train)...
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/token_length_by_label.png

  Median token count by label:
    positive          : 44 tokens  (mean=63)
    neutral           : 60 tokens  (mean=80)
    negative          : 28 tokens  (mean=56)
    not_mentioned     : 10 tokens  (mean=23)

[4/10] Negation frequency by label (train)...
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/negation_by_label.png

  Mean negation tokens per post by label:
    positive          : 1.573
    neutral           : 2.339
    negative          : 1.796
    not_mentioned     : 0.654

[5/10] N-grams (train)...
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/ngrams_functional_positive.png
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/ngrams_functional_negative.png

[6/10] Word clouds (train)...

  [positive] Top 10 words:
    ai                     ████████████████████
    therapist              ███████████████████
    people                 ████████████████
    therapy                ███████████████
    chatgpt                █████████████
    help                   ███████████
    work                   ██████████
    thing                  █████████
    need                   ████████
    one                    ████████

  [negative] Top 10 words:
    ai                     ████████████████████
    therapy                █████████████
    human                  █████████
    user                   ████████
    people                 ███████
    therapist              ███████
    thing                  ██████
    trademark              ██████
    make                   ██████
    even                   ██████
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/wordclouds_functional.png

[7/10] Posts over time (test)...
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/posts_over_time.png

  Monthly activity:
type     comment  post
month
2025-04       83    27
2025-05      619    58
2025-06      972    72
2025-07     1886   100
2025-08     1789    97
2025-09     2730   128
2025-10     1180    73
2025-11     1512    69
2025-12     2514    92
2026-01     5147    92

[8/10] Score distribution (test)...
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/score_distribution.png

  Score stats:
           count       mean        std   min  25%  50%   75%    max
type
comment  18432.0   2.450195   4.567332 -33.0  1.0  1.0   2.0  250.0
post       808.0  17.548267  32.963239   0.0  2.0  8.0  18.0  384.0

[9/10] High engagement word cloud (test)...
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/high_engagement_wordcloud.png

  Top words in high-engagement posts (score ≥ 50):
    ai                     ████████████████████
    chatgpt                █████████████████
    therapy                ████████████████
    people                 ████████████████
    therapist              █████████████
    feel                   █████████████
    thing                  ████████████
    help                   ███████████
    life                   ███████████
    way                    ██████████

[10/10] Summary report...
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/eda_summary.txt

=================================================================
EDA SUMMARY — AI Mental Health Reddit Study
Functional Factor
=================================================================

Training set :    801 posts
Test set     : 19,240 posts
Date range   : April 2025 – January 2026 (278 days)

── Quality Flags ────────────────────────────────────────
  is_removed          train=1   test=2
  is_image            train=5   test=0
  too_short           train=133   test=2826

── Token Length (Train) ─────────────────────────────────
count    801.000000
mean      38.836454
std       60.516336
min        0.000000
25%        7.000000
50%       19.000000
75%       45.000000
max      584.000000

── Functional Label Distribution (Train) ────────────────
  not_mentioned     :  497  (62.0%)
  positive          :  192  (24.0%)
  neutral           :   56  (7.0%)
  negative          :   54  (6.7%)

  Imbalance ratio (excl. not_mentioned): 3.6x
  ⚠️  Notable imbalance — use class weights in model

── Test Set Engagement ──────────────────────────────────
  Posts    : 808
  Comments : 18,432
  High engagement (score≥50) : 90
  Median score (posts)    : 8
  Median score (comments) : 1

=================================================================

✅ EDA complete. All plots saved to /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/

# 4. Classification (using HuggingFace's mental/mental-roberta-base)

In [14]:
import torch 
print(f"Is CUDA available: {torch.cuda.is_available()}")

if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name()}")
else:
    print("GPU not available")

Is CUDA available: False
GPU not available

In [ ]:
output_dir = "/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/output_dir"
data_dir   = "/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input"
num_epochs = 10
hf_token   = "YOUR_HF_TOKEN"

In [16]:
cmd = (
    f"classification.py"
    f" --train      {train_path}"
    f" --test       {test_path}"
    f" --output_dir {output_dir}"
    f" --data_dir   {data_dir}"
    f" --epochs     {num_epochs}"
    f" --hf_token   {hf_token}"
)

%run $cmd

Device: cpu

 Loading Training Data
 Shape of Training Data: (801, 6)

 Loading Test Data
 Shape of Test Data: (19240, 11)
Shape of Training Data after Filtering: (667, 6)
       negative ( -1): 54
        neutral (  0): 56
       positive (  1): 190
  not_mentioned ( 99): 367
 SUMMARY:
Training Dataset: 533Testing Dataset: 134

 Loading tokenizer (mental/mental-roberta-base)
Loading Model: (mental/mental-roberta-base)

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at mental/mental-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Class weights: {'negative': '3.10', 'neutral': '2.96', 'positive': '0.88', 'not_mentioned': '0.45'}
 Training for 10 epochs
 Epoch 1/10 train_loss = 1.3921 | train_accuracy = 0.2364 val_loss = 1.3565 | val_accuracy = 0.4030
 Best model so far saved to /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/output_dir/best_model best validation loss = 1.3565
 Epoch 2/10 train_loss = 1.3459 | train_accuracy = 0.4015 val_loss = 1.3312 | val_accuracy = 0.5522
 Best model so far saved to /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/output_dir/best_model best validation loss = 1.3312
 Epoch 3/10 train_loss = 1.2226 | train_accuracy = 0.6041 val_loss = 1.3102 | val_accuracy = 0.6045
 Best model so far saved to /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/output_dir/best_model best validation loss = 1.3102
 Epoch 4/10 train_loss = 1.0811 | train_accuracy = 0.5741 val_loss = 1.4130 | val_accuracy = 0.5149
 Epoch 5/10 train_loss = 0.9048 | train_accuracy = 0.6510 val_loss = 1.5129 | val_accuracy = 0.5746
 Epoch 6/10 train_loss = 0.6984 | train_accuracy = 0.7467 val_loss = 1.3654 | val_accuracy = 0.4925
 Epoch 7/10 train_loss = 0.5159 | train_accuracy = 0.8330 val_loss = 1.5017 | val_accuracy = 0.5746
 Epoch 8/10 train_loss = 0.3601 | train_accuracy = 0.8780 val_loss = 1.5546 | val_accuracy = 0.5522
 Epoch 9/10 train_loss = 0.2757 | train_accuracy = 0.9118 val_loss = 1.6285 | val_accuracy = 0.5448
 Epoch 10/10 train_loss = 0.2312 | train_accuracy = 0.9287 val_loss = 1.8133 | val_accuracy = 0.5970
CLASSIFICATION REPORT (Validation Set Only)
               precision    recall  f1-score   support

     negative       0.20      0.09      0.12        11
      neutral       0.50      0.18      0.27        11
not_mentioned       0.75      0.69      0.72        74
     positive       0.47      0.71      0.57        38

     accuracy                           0.60       134
    macro avg       0.48      0.42      0.42       134
 weighted avg       0.61      0.60      0.59       134

Classification Report saved to /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/output_dir/classification_report.txt
 Confusion Matrix save to /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/output_dir/confusion_matrix.png
Loading best model for test set classifications


 Predicted Label Distribution (Test Set):
functional_label
not_mentioned    12059
positive          6268
negative           509
neutral            404

  Low-confidence rows: 8811
 Save test Set Prediction here: /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/test_withPred.csv
 Save Low_Confidence Set Prediction here: /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/low_conf_review.csv
Done

In [17]:
test_df = pd.read_csv("/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/test_withPred.csv")
lowconf_df = pd.read_csv("/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/low_conf_review.csv")

In [18]:
len(test_df)

19240

In [19]:
len(lowconf_df)

8811

# 5. Low Confidence Review using CatLLM

In [7]:
# CatLLM is compatible on Python versions over 3.10+
import sys
print(sys.version)

3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:54:21) [Clang 16.0.6 ]

In [8]:
!pip install groq

Requirement already satisfied: groq in /opt/anaconda3/lib/python3.12/site-packages (1.1.2)
Requirement already satisfied: anyio<5,>=3.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (4.2.0)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (0.27.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (2.8.2)
Requirement already satisfied: sniffio in /opt/anaconda3/lib/python3.12/site-packages (from groq) (1.3.0)
Requirement already satisfied: typing-extensions<5,>=4.14 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in /opt/anaconda3/lib/python3.12/site-packages (from anyio<5,>=3.5.0->groq) (3.7)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->groq) (2025.8.3)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->groq) (1.0.2)
Requirement already satisfied: h11<0.15,>=0.13 in /opt/anaconda3/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->groq) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->groq) (2.20.1)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [9]:
!pip install cat-llm

Requirement already satisfied: cat-llm in /opt/anaconda3/lib/python3.12/site-packages (3.0.0)
Requirement already satisfied: cat-ademic>=0.1.1 in /opt/anaconda3/lib/python3.12/site-packages (from cat-llm) (0.1.2)
Requirement already satisfied: cat-cog>=0.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from cat-llm) (0.1.0)
Requirement already satisfied: cat-pol>=0.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from cat-llm) (1.1.0)
Requirement already satisfied: cat-stack>=0.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from cat-llm) (1.0.7)
Requirement already satisfied: cat-survey>=0.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from cat-llm) (0.1.0)
Requirement already satisfied: cat-vader>=1.13.0 in /opt/anaconda3/lib/python3.12/site-packages (from cat-llm) (1.13.1)
Requirement already satisfied: cat-web>=0.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from cat-llm) (0.1.0)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.12/site-packages (from cat-ademic>=0.1.1->cat-llm) (2.3.0)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.12/site-packages (from cat-ademic>=0.1.1->cat-llm) (2.32.3)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.12/site-packages (from cat-ademic>=0.1.1->cat-llm) (4.66.5)
Requirement already satisfied: anthropic in /opt/anaconda3/lib/python3.12/site-packages (from cat-stack>=0.1.0->cat-llm) (0.86.0)
Requirement already satisfied: openai in /opt/anaconda3/lib/python3.12/site-packages (from cat-stack>=0.1.0->cat-llm) (1.93.0)
Requirement already satisfied: perplexityai in /opt/anaconda3/lib/python3.12/site-packages (from cat-stack>=0.1.0->cat-llm) (0.31.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from anthropic->cat-stack>=0.1.0->cat-llm) (4.2.0)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from anthropic->cat-stack>=0.1.0->cat-llm) (1.9.0)
Requirement already satisfied: docstring-parser<1,>=0.15 in /opt/anaconda3/lib/python3.12/site-packages (from anthropic->cat-stack>=0.1.0->cat-llm) (0.17.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /opt/anaconda3/lib/python3.12/site-packages (from anthropic->cat-stack>=0.1.0->cat-llm) (0.27.0)
Requirement already satisfied: jiter<1,>=0.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from anthropic->cat-stack>=0.1.0->cat-llm) (0.10.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /opt/anaconda3/lib/python3.12/site-packages (from anthropic->cat-stack>=0.1.0->cat-llm) (2.8.2)
Requirement already satisfied: sniffio in /opt/anaconda3/lib/python3.12/site-packages (from anthropic->cat-stack>=0.1.0->cat-llm) (1.3.0)
Requirement already satisfied: typing-extensions<5,>=4.14 in /opt/anaconda3/lib/python3.12/site-packages (from anthropic->cat-stack>=0.1.0->cat-llm) (4.15.0)
Requirement already satisfied: idna>=2.8 in /opt/anaconda3/lib/python3.12/site-packages (from anyio<5,>=3.5.0->anthropic->cat-stack>=0.1.0->cat-llm) (3.7)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.12/site-packages (from httpx<1,>=0.25.0->anthropic->cat-stack>=0.1.0->cat-llm) (2025.8.3)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.12/site-packages (from httpx<1,>=0.25.0->anthropic->cat-stack>=0.1.0->cat-llm) (1.0.2)
Requirement already satisfied: h11<0.15,>=0.13 in /opt/anaconda3/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.25.0->anthropic->cat-stack>=0.1.0->cat-llm) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->anthropic->cat-stack>=0.1.0->cat-llm) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->anthropic->cat-stack>=0.1.0->cat-llm) (2.20.1)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.12/site-packages (from pandas->cat-ademic>=0.1.1->cat-llm) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas->cat-ademic>=0.1.1->cat-llm) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas->cat-ademic>=0.1.1->cat-llm) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas->cat-ademic>=0.1.1->cat-llm) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->cat-ademic>=0.1.1->cat-llm) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests->cat-ademic>=0.1.1->cat-llm) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests->cat-ademic>=0.1.1->cat-llm) (2.4.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [ ]:
pred_data_path = "/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/test_withPred.csv"
lowconf_data_path = "/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/low_conf_review.csv"
data_dir   = "/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input"
llm_model = "llama-3.1-8b-instant"
groq_key = "YOUR_GROQ_KEY"

In [14]:
cmd = (
    f"lowconf_data_review.py"
    f" --predictions {pred_data_path}"
    f" --low_conf    {lowconf_data_path}"
    f" --output_dir  {data_dir}"
    f" --llm_model   llama-3.1-8b-instant"
    f" --groq_key  {groq_key}"
)
%run $cmd

 CatLLM Review


 Loading Full Predictions -> /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/test_withPred.csv
 Shape : (19240, 15)
  Loading low-conf subset -> /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/low_conf_review.csv
 Shape: (8811, 15)  (45.8% of test set)

  Running CatLLM (llama-3.1-8b-instant) on 8,811 low-confidence rows...
  Resuming from row 8811 (8811 rows already done)

  CatLLM predicted distribution:
catllm_label
not_mentioned    8760
negative           21
neutral            18
positive           12

 Agreement between mental/mental-roberta-base and CatLLM:
 Total Compared: 8,811
 Agree : 7,388 (83.8%)
 Disgree : 1,423  (16.2%)

 Disagreement Breakdown:
roberta_label  catllm_label
positive       not_mentioned    762
negative       not_mentioned    471
neutral        not_mentioned    149
not_mentioned  neutral           11
               negative          10
               positive           6
positive       negative           6
               neutral            3
neutral        negative           2
negative       neutral            1
Audit File saved to /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/catllm_review.csv

  Merging CatLLM predictions into full dataset...

  Final label distribution (merged):
final_label
not_mentioned    13414
positive          5505
neutral            267
negative            54
 Final predictions saved to /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input
  Audit (both predictions) saved to /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/catllm_review.csv
  Final merged predictions saved to /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/test_finalPreds.csv

In [15]:
test_df = pd.read_csv("/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/test_finalPreds.csv")

In [20]:
print(f"\n SUMMARY: \n"
      f"\n 1. Length of train dataset: {len(pd.read_csv("/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/train.csv"))} \n"
      f"\n 2. Length of inital test dataset: {len(pd.read_csv("/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/test.csv"))} \n"
      f"\n 3. Length of test dataset before CatLLM classification (with undertainity): {len(pd.read_csv("/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/test_withPred.csv"))} \n"
      f"\n 4. Length of uncertain rows in test dataset: {len(pd.read_csv("/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/low_conf_review.csv"))} \n"
      f"\n 5. Length of rows classified by CatLLM: {len(pd.read_csv("/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/catllm_review.csv"))} \n"
      f"\n 6. Length of final test dataset after verified classification: {len(test_df)} \n"
      )

 SUMMARY:

 1. Length of train dataset: 801

 2. Length of inital test dataset: 19240

 3. Length of test dataset before CatLLM classification (with undertainity): 19240

 4. Length of uncertain rows in test dataset: 8811

 5. Length of rows classified by CatLLM: 8811

 6. Length of final test dataset after verified classification: 19240

# 6. Annotation Agreement (Human Annotations (vs) CatLLM classification)

*As ground truth labels are unavailable for the test set, model reliability was assessed through two complementary approaches:*
- *(1) inter-annotator agreement between human coders and CatLLM on the labeled training set (Cohen's κ = X), and*
- *(2) validation set performance of MentalRoBERTa (macro F1 = X). Low-confidence predictions (< 0.40, n = 8,811, 45.8%) were additionally reviewed by CatLLM to improve label quality.*

In [21]:
!pip install groq krippendorff scikit-learn

Requirement already satisfied: groq in /opt/anaconda3/lib/python3.12/site-packages (1.1.2)
Collecting krippendorff
  Downloading krippendorff-0.8.2-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.12/site-packages (1.8.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (4.2.0)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (0.27.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (2.8.2)
Requirement already satisfied: sniffio in /opt/anaconda3/lib/python3.12/site-packages (from groq) (1.3.0)
Requirement already satisfied: typing-extensions<5,>=4.14 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in /opt/anaconda3/lib/python3.12/site-packages (from anyio<5,>=3.5.0->groq) (3.7)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->groq) (2025.8.3)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->groq) (1.0.2)
Requirement already satisfied: h11<0.15,>=0.13 in /opt/anaconda3/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->groq) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->groq) (2.20.1)
Requirement already satisfied: numpy<3,>=1.21 in /opt/anaconda3/lib/python3.12/site-packages (from krippendorff) (1.26.4)
Requirement already satisfied: scipy>=1.10.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn) (3.5.0)
Downloading krippendorff-0.8.2-py3-none-any.whl (18 kB)
Installing collected packages: krippendorff
Successfully installed krippendorff-0.8.2

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [25]:
train_path = train_path
output_path = data_dir
groq_key = groq_key

In [26]:
cmd = (
    f"annotation_agreement.py"
    f" --train     {train_path}"
    f" --output    {output_path}"
    f" --groq_key  {groq_key}"
)
%run $cmd

  Annotation Agreement: Human vs CatLLM


  Loading training data from /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/train.csv...
  Total training samples: 801 (801 rows, 6 columns)

  Human label distribution:
human_label
not_mentioned    497
positive         192
neutral           56
negative          54
  Testing Groq API key...
  ✓ Key valid. Response: ok
  Processed 50/799 rows...
  Processed 100/799 rows...
  Processed 150/799 rows...
  Processed 200/799 rows...
  Processed 250/799 rows...
  Processed 300/799 rows...
  Processed 350/799 rows...
  Processed 400/799 rows...
  Processed 450/799 rows...
  Processed 500/799 rows...
  Processed 550/799 rows...
  Processed 600/799 rows...
  Processed 650/799 rows...
  Processed 700/799 rows...
  Processed 750/799 rows...

  CatLLM label distribution:
catllm_label
not_mentioned    364
positive         180
negative         130
neutral          125

  Labelled file saved → /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/catllm_traindf.csv

  Total valid samples for agreement: 799

  Human vs CatLLM Agreement:

 N (valid samples): 799

  Raw Agreement: 0.6809 (Substantial)

  Cohen's Kappa: 0.5017 (Moderate)

  Krippendorff's Alpha: 0.4933 (Moderate)

 Disagreement Breakdown:

 Label           Human      CatLLM     Agreement

 negative        54         130        77.78%

 neutral         56         125        41.07%

 positive        192        180        70.83%

 not_mentioned   497        364        69.01%
  ✓ Confusion matrix saved → /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/agreement_confusion.png
  Agreement report saved → /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/agreementreport_summary.txt
  Confusion matrix saved → /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/agreement_confusion.png

  All outputs saved to /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input

# 7. Thematic Analysis

In [27]:
!pip install bertopic sentence-transformers umap-learn hdbscan

Requirement already satisfied: bertopic in /opt/anaconda3/lib/python3.12/site-packages (0.17.4)
Requirement already satisfied: sentence-transformers in /opt/anaconda3/lib/python3.12/site-packages (4.1.0)
Requirement already satisfied: umap-learn in /opt/anaconda3/lib/python3.12/site-packages (0.5.11)
Requirement already satisfied: hdbscan in /opt/anaconda3/lib/python3.12/site-packages (0.8.41)
Requirement already satisfied: numpy>=1.20.0 in /opt/anaconda3/lib/python3.12/site-packages (from bertopic) (1.26.4)
Requirement already satisfied: pandas>=1.1.5 in /opt/anaconda3/lib/python3.12/site-packages (from bertopic) (2.3.0)
Requirement already satisfied: plotly>=4.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /opt/anaconda3/lib/python3.12/site-packages (from bertopic) (1.8.0)
Requirement already satisfied: tqdm>=4.41.1 in /opt/anaconda3/lib/python3.12/site-packages (from bertopic) (4.66.5)
Requirement already satisfied: llvmlite>0.36.0 in /opt/anaconda3/lib/python3.12/site-packages (from bertopic) (0.43.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (4.52.4)
Requirement already satisfied: torch>=1.11.0 in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (2.5.1)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (0.32.3)
Requirement already satisfied: Pillow in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (10.4.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (3.13.1)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.9.11)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.5.3)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.6.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /opt/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.1.2)
Requirement already satisfied: numba>=0.51.2 in /opt/anaconda3/lib/python3.12/site-packages (from umap-learn) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /opt/anaconda3/lib/python3.12/site-packages (from umap-learn) (0.6.0)
Requirement already satisfied: joblib>=1.0 in /opt/anaconda3/lib/python3.12/site-packages (from hdbscan) (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.1.5->bertopic) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.1.5->bertopic) (2023.3)
Requirement already satisfied: tenacity>=6.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from plotly>=4.7.0->bertopic) (8.2.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.16.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn>=1.0->bertopic) (3.5.0)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (75.1.0)
Requirement already satisfied: sympy==1.13.1 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: networkx in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (3.3)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.8.3)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [28]:
input_path = "/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/test_finalPreds.csv"
plot_path = "/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis"
output_path = "/Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/output"

In [29]:
cmd = (
    f"thematic_analysis.py"
    f" --input      {input_path}"
    f" --plots      {plot_path}"
    f" --output     {output_path}"
)

%run $cmd

============================================================
  Thematic Analysis — AI Mental Health Reddit
============================================================

[1/6] Loading data from /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/data/processed_input/test_finalPreds.csv...
  Using 'final_label' column (post CatLLM review)
  Loaded 19,186 rows with valid text.

[2/6] Plotting label distribution...
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/label_distribution.png

[3/6] Plotting word frequency per label...
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/word_frequency_per_label.png

[4/6] Plotting sentiment share over time...
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/sentiment_over_time.png

[5/6] Running BERTopic per sentiment label...

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

  [negative]  53 posts
    Found 0 topics  |  Outliers: 53

  [neutral]  265 posts
    Found 4 topics  |  Outliers: 133
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/topics_neutral.png
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/topic_words_neutral.png

  [positive]  5,505 posts
    Found 29 topics  |  Outliers: 3,031
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/topics_positive.png
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/topic_words_positive.png

  [not_mentioned]  13,363 posts
    Found 153 topics  |  Outliers: 6,101
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/topics_not_mentioned.png
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/topic_words_not_mentioned.png

  Topic summary saved → /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/output/all_topics.csv

[6/6] Topics over time for all labels...
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/topics_over_time_neutral.png
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/topics_over_time_positive.png
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/topics_over_time_not_mentioned.png

[+] High-engagement topic analysis...

  High-engagement posts (score ≥ 50): 90
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/high_engagement_label_dist.png
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/high_eng_words_positive.png
  ✓ /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/high_eng_words_not_mentioned.png

============================================================
  Thematic analysis complete.
  Plots   → /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis
  Topics  → /Users/khnsakhnm/Documents/MentalHealth_Research/AI4MH-Reddit/Plots/thematic_analysis/outputall_topics.csv
============================================================

In [30]:
topics_df = pd.read_csv(os.path.join(output_path, "all_topics.csv"))
print(f"Total topics found: {len(topics_df)}")
topics_df.groupby("label")[["Topic", "Count", "Name"]].head(5)

Total topics found: 186

    Topic  Count                               Name
0       0     35             0_truth_feel_even_fear
1       1     34      1_ai_therapy_therapist_people
2       2     32    2_therapist_therapy_also_people
3       3     31          3_people_thing_like_think
4       0   1064      0_ai_therapy_therapist_people
5       1    232  1_therapist_therapy_people_client
6       2    227    2_chatgpt_gpt_therapist_therapy
7       3    176   3_therapist_trauma_cptsd_therapy
8       4     83           4_life_year_therapy_work
33      0    608      0_therapist_therapy_human_one
34      1    397     1_argument_faith_point_comment
35      2    308      2_ai_therapy_therapist_mental
36      3    252                3_ai_human_tool_use
37      4    218      4_gpt_custom_gpts_instruction

1. https://www.geeksforgeeks.org/machine-learning/python-lemmatization-approaches-with-examples/
2. https://www.geeksforgeeks.org/machine-learning/introduction-to-stemming/
3. https://www.geeksforgeeks.org/dsa/write-regular-expressions/
4. https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0318464
5. https://huggingface.co/spaces/CatLLM/survey-classifier